services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: busnurd-app-prod
    restart: always
    env_file:
      - .env
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
